<?php
/** @var $block \Magento\Catalog\Block\Product\View */
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <span class="minus"><button type="button" title="<?= $block->escapeHtmlAttr(__('Reduce the quantity')); ?>">-</button></span>
                        <input type="number"
                                name="qty"
                                id="qty"
                                maxlength="12"
                                value="<?= $block->escapeHtmlAttr($block->getProductDefaultQty() * 1) ?>"
                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty"
                                data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span class="plus"><button type="button" title="<?= $block->escapeHtmlAttr(__('Increase the quantity')); ?>"/>+</button></span>
                        <script type="text/javascript">
                            // This is the javascript codes help us to increase and decrease qty
                            require(['jquery'], function ($) {
                                $('.box-tocart .minus').on('click', function () {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty - 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('.box-tocart .plus').on('click', function () {
                                    var qty = parseInt($('#qty').val());
                                    qty = qty + 1;
                                    $('#qty').val(qty).trigger('change');
                                });
                                $('#qty').on('change', function () {
                                    var qty = parseInt($(this).val());
                                    if (qty > 100) {
                                        $(this).val('100');
                                    } else if (qty < 1) {
                                        $(this).val('1');
                                    }
                                });
                            });
                        </script>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->escapeHtml($block->getChildHtml('', true)) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
<?php endif; ?>
